"""empty message

Revision ID: f9efd24e254d
Revises: a7a2c6de2a0a
Create Date: 2016-06-12 11:34:26.956058

"""

# revision identifiers, used by Alembic.
revision = 'f9efd24e254d'
down_revision = 'a7a2c6de2a0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('post', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('post', 'publication_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'title',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('post', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('post', 'publication_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('post', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('post', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    ### end Alembic commands ###
